# Generated by Django 2.2.16 on 2020-10-11 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('blog', '0005_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
